// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0--rc3
// source: domain/schedules/proto/schedules_dto.proto

package schedules

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScheduleClient is the client API for Schedule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleClient interface {
	CreateSchedule(ctx context.Context, in *ScheduleCreateProto, opts ...grpc.CallOption) (*ScheduleProto, error)
	FindScheduleAll(ctx context.Context, in *FindScheduleProto, opts ...grpc.CallOption) (*ListscheduledetailProto, error)
	FindScheduleAvailable(ctx context.Context, in *FindScheduleProto, opts ...grpc.CallOption) (*ListscheduledetailProto, error)
	FindScheduleBooked(ctx context.Context, in *FindScheduleProto, opts ...grpc.CallOption) (*ListscheduledetailProto, error)
	BookSlot(ctx context.Context, in *SetScheduleProto, opts ...grpc.CallOption) (*ScheduledetailProto, error)
}

type scheduleClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleClient(cc grpc.ClientConnInterface) ScheduleClient {
	return &scheduleClient{cc}
}

func (c *scheduleClient) CreateSchedule(ctx context.Context, in *ScheduleCreateProto, opts ...grpc.CallOption) (*ScheduleProto, error) {
	out := new(ScheduleProto)
	err := c.cc.Invoke(ctx, "/schedules.Schedule/CreateSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleClient) FindScheduleAll(ctx context.Context, in *FindScheduleProto, opts ...grpc.CallOption) (*ListscheduledetailProto, error) {
	out := new(ListscheduledetailProto)
	err := c.cc.Invoke(ctx, "/schedules.Schedule/FindScheduleAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleClient) FindScheduleAvailable(ctx context.Context, in *FindScheduleProto, opts ...grpc.CallOption) (*ListscheduledetailProto, error) {
	out := new(ListscheduledetailProto)
	err := c.cc.Invoke(ctx, "/schedules.Schedule/FindScheduleAvailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleClient) FindScheduleBooked(ctx context.Context, in *FindScheduleProto, opts ...grpc.CallOption) (*ListscheduledetailProto, error) {
	out := new(ListscheduledetailProto)
	err := c.cc.Invoke(ctx, "/schedules.Schedule/FindScheduleBooked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleClient) BookSlot(ctx context.Context, in *SetScheduleProto, opts ...grpc.CallOption) (*ScheduledetailProto, error) {
	out := new(ScheduledetailProto)
	err := c.cc.Invoke(ctx, "/schedules.Schedule/BookSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServer is the server API for Schedule service.
// All implementations must embed UnimplementedScheduleServer
// for forward compatibility
type ScheduleServer interface {
	CreateSchedule(context.Context, *ScheduleCreateProto) (*ScheduleProto, error)
	FindScheduleAll(context.Context, *FindScheduleProto) (*ListscheduledetailProto, error)
	FindScheduleAvailable(context.Context, *FindScheduleProto) (*ListscheduledetailProto, error)
	FindScheduleBooked(context.Context, *FindScheduleProto) (*ListscheduledetailProto, error)
	BookSlot(context.Context, *SetScheduleProto) (*ScheduledetailProto, error)
	mustEmbedUnimplementedScheduleServer()
}

// UnimplementedScheduleServer must be embedded to have forward compatible implementations.
type UnimplementedScheduleServer struct {
}

func (UnimplementedScheduleServer) CreateSchedule(context.Context, *ScheduleCreateProto) (*ScheduleProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedScheduleServer) FindScheduleAll(context.Context, *FindScheduleProto) (*ListscheduledetailProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindScheduleAll not implemented")
}
func (UnimplementedScheduleServer) FindScheduleAvailable(context.Context, *FindScheduleProto) (*ListscheduledetailProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindScheduleAvailable not implemented")
}
func (UnimplementedScheduleServer) FindScheduleBooked(context.Context, *FindScheduleProto) (*ListscheduledetailProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindScheduleBooked not implemented")
}
func (UnimplementedScheduleServer) BookSlot(context.Context, *SetScheduleProto) (*ScheduledetailProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookSlot not implemented")
}
func (UnimplementedScheduleServer) mustEmbedUnimplementedScheduleServer() {}

// UnsafeScheduleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServer will
// result in compilation errors.
type UnsafeScheduleServer interface {
	mustEmbedUnimplementedScheduleServer()
}

func RegisterScheduleServer(s grpc.ServiceRegistrar, srv ScheduleServer) {
	s.RegisterService(&Schedule_ServiceDesc, srv)
}

func _Schedule_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleCreateProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedules.Schedule/CreateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServer).CreateSchedule(ctx, req.(*ScheduleCreateProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedule_FindScheduleAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindScheduleProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServer).FindScheduleAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedules.Schedule/FindScheduleAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServer).FindScheduleAll(ctx, req.(*FindScheduleProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedule_FindScheduleAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindScheduleProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServer).FindScheduleAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedules.Schedule/FindScheduleAvailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServer).FindScheduleAvailable(ctx, req.(*FindScheduleProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedule_FindScheduleBooked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindScheduleProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServer).FindScheduleBooked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedules.Schedule/FindScheduleBooked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServer).FindScheduleBooked(ctx, req.(*FindScheduleProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedule_BookSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScheduleProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServer).BookSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedules.Schedule/BookSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServer).BookSlot(ctx, req.(*SetScheduleProto))
	}
	return interceptor(ctx, in, info, handler)
}

// Schedule_ServiceDesc is the grpc.ServiceDesc for Schedule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Schedule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedules.Schedule",
	HandlerType: (*ScheduleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchedule",
			Handler:    _Schedule_CreateSchedule_Handler,
		},
		{
			MethodName: "FindScheduleAll",
			Handler:    _Schedule_FindScheduleAll_Handler,
		},
		{
			MethodName: "FindScheduleAvailable",
			Handler:    _Schedule_FindScheduleAvailable_Handler,
		},
		{
			MethodName: "FindScheduleBooked",
			Handler:    _Schedule_FindScheduleBooked_Handler,
		},
		{
			MethodName: "BookSlot",
			Handler:    _Schedule_BookSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/schedules/proto/schedules_dto.proto",
}
