// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0--rc3
// source: domain/paramedics/proto/paramedic_dto.proto

package paramedics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamedicCreateProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname  string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname   string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email      string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Usercreate string `protobuf:"bytes,4,opt,name=usercreate,proto3" json:"usercreate,omitempty"`
}

func (x *ParamedicCreateProto) Reset() {
	*x = ParamedicCreateProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamedicCreateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamedicCreateProto) ProtoMessage() {}

func (x *ParamedicCreateProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamedicCreateProto.ProtoReflect.Descriptor instead.
func (*ParamedicCreateProto) Descriptor() ([]byte, []int) {
	return file_domain_paramedics_proto_paramedic_dto_proto_rawDescGZIP(), []int{0}
}

func (x *ParamedicCreateProto) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *ParamedicCreateProto) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *ParamedicCreateProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ParamedicCreateProto) GetUsercreate() string {
	if x != nil {
		return x.Usercreate
	}
	return ""
}

type ParamedicFindByHospitalProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hospitalid string `protobuf:"bytes,1,opt,name=hospitalid,proto3" json:"hospitalid,omitempty"`
}

func (x *ParamedicFindByHospitalProto) Reset() {
	*x = ParamedicFindByHospitalProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamedicFindByHospitalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamedicFindByHospitalProto) ProtoMessage() {}

func (x *ParamedicFindByHospitalProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamedicFindByHospitalProto.ProtoReflect.Descriptor instead.
func (*ParamedicFindByHospitalProto) Descriptor() ([]byte, []int) {
	return file_domain_paramedics_proto_paramedic_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ParamedicFindByHospitalProto) GetHospitalid() string {
	if x != nil {
		return x.Hospitalid
	}
	return ""
}

type ParamedicProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paramedicid string `protobuf:"bytes,1,opt,name=paramedicid,proto3" json:"paramedicid,omitempty"`
	Firstname   string `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname    string `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ParamedicProto) Reset() {
	*x = ParamedicProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamedicProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamedicProto) ProtoMessage() {}

func (x *ParamedicProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamedicProto.ProtoReflect.Descriptor instead.
func (*ParamedicProto) Descriptor() ([]byte, []int) {
	return file_domain_paramedics_proto_paramedic_dto_proto_rawDescGZIP(), []int{2}
}

func (x *ParamedicProto) GetParamedicid() string {
	if x != nil {
		return x.Paramedicid
	}
	return ""
}

func (x *ParamedicProto) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *ParamedicProto) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *ParamedicProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListparamedicProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paramedics []*ParamedicProto `protobuf:"bytes,1,rep,name=paramedics,proto3" json:"paramedics,omitempty"`
}

func (x *ListparamedicProto) Reset() {
	*x = ListparamedicProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListparamedicProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListparamedicProto) ProtoMessage() {}

func (x *ListparamedicProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListparamedicProto.ProtoReflect.Descriptor instead.
func (*ListparamedicProto) Descriptor() ([]byte, []int) {
	return file_domain_paramedics_proto_paramedic_dto_proto_rawDescGZIP(), []int{3}
}

func (x *ListparamedicProto) GetParamedics() []*ParamedicProto {
	if x != nil {
		return x.Paramedics
	}
	return nil
}

var File_domain_paramedics_proto_paramedic_dto_proto protoreflect.FileDescriptor

var file_domain_paramedics_proto_paramedic_dto_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64,
	0x69, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x64, 0x69, 0x63, 0x5f, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x64, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x22,
	0x3e, 0x0a, 0x1c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x64, 0x22,
	0x82, 0x01, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0x50, 0x0a, 0x12, 0x6c, 0x69, 0x73, 0x74, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3a, 0x0a, 0x0a, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x32, 0xbc, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x64, 0x69, 0x63, 0x12, 0x51, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x12, 0x20, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x64, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x79, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x12, 0x28, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x73,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_paramedics_proto_paramedic_dto_proto_rawDescOnce sync.Once
	file_domain_paramedics_proto_paramedic_dto_proto_rawDescData = file_domain_paramedics_proto_paramedic_dto_proto_rawDesc
)

func file_domain_paramedics_proto_paramedic_dto_proto_rawDescGZIP() []byte {
	file_domain_paramedics_proto_paramedic_dto_proto_rawDescOnce.Do(func() {
		file_domain_paramedics_proto_paramedic_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_paramedics_proto_paramedic_dto_proto_rawDescData)
	})
	return file_domain_paramedics_proto_paramedic_dto_proto_rawDescData
}

var file_domain_paramedics_proto_paramedic_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_paramedics_proto_paramedic_dto_proto_goTypes = []interface{}{
	(*ParamedicCreateProto)(nil),         // 0: paramedics.paramedicCreateProto
	(*ParamedicFindByHospitalProto)(nil), // 1: paramedics.paramedicFindByHospitalProto
	(*ParamedicProto)(nil),               // 2: paramedics.paramedicProto
	(*ListparamedicProto)(nil),           // 3: paramedics.listparamedicProto
}
var file_domain_paramedics_proto_paramedic_dto_proto_depIdxs = []int32{
	2, // 0: paramedics.listparamedicProto.paramedics:type_name -> paramedics.paramedicProto
	0, // 1: paramedics.Paramedic.CreateParamedic:input_type -> paramedics.paramedicCreateProto
	1, // 2: paramedics.Paramedic.FindByHospital:input_type -> paramedics.paramedicFindByHospitalProto
	2, // 3: paramedics.Paramedic.CreateParamedic:output_type -> paramedics.paramedicProto
	3, // 4: paramedics.Paramedic.FindByHospital:output_type -> paramedics.listparamedicProto
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_paramedics_proto_paramedic_dto_proto_init() }
func file_domain_paramedics_proto_paramedic_dto_proto_init() {
	if File_domain_paramedics_proto_paramedic_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamedicCreateProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamedicFindByHospitalProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamedicProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_paramedics_proto_paramedic_dto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListparamedicProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_paramedics_proto_paramedic_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_paramedics_proto_paramedic_dto_proto_goTypes,
		DependencyIndexes: file_domain_paramedics_proto_paramedic_dto_proto_depIdxs,
		MessageInfos:      file_domain_paramedics_proto_paramedic_dto_proto_msgTypes,
	}.Build()
	File_domain_paramedics_proto_paramedic_dto_proto = out.File
	file_domain_paramedics_proto_paramedic_dto_proto_rawDesc = nil
	file_domain_paramedics_proto_paramedic_dto_proto_goTypes = nil
	file_domain_paramedics_proto_paramedic_dto_proto_depIdxs = nil
}
